### ISSUE TITLE
Bowerに登録する予定はありますか？

### ISSUE THREAD

**Issue by lion-man44** [webcyou/MessageViewJS#13]
自分は今、Railsでこれを利用しようとしていて、もし良ければbowerに登録してくれると助かります

**Comment by webcyou** [comment]
コメントありがとうございます mm
はい。追って対応させていただこうかと思います。

引き続きよろしくお願いいたします。

**Comment by lion-man44** [comment]
なるほど、ありがとうございます。
それではCloseします。
