### ISSUE TITLE
質問等を受け取れるような機構はあったりしますか？

### ISSUE THREAD

**Issue by lion-man44** [webcyou/MessageViewJS#15]
恋愛アドベンチャーゲームでよくあるような質問を受けて、選択肢を選ぶような機構はあったりしますか？
またはそのようなロードマップは引いていたりしますか？

**Comment by webcyou** [comment]
コメントありがとうございます mm

＞質問を受けて、選択肢を選ぶような〜
特にその辺に特化して設計しておりませんが、callbackなりサーバーとの通信を行うなどをすることによって実装は可能かと思われます。

例として、今後Demoでも追加していければと思っております。

**Comment by lion-man44** [comment]
返事ありがとうございます

> callbackなりサーバーとの...

ですよね
ただ、MessageViewJS側で吸収出来ると楽しいかもしれませんね
